/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import javax.swing.JOptionPane;

/**
 *
 * @author SovTur
 */
public class framelogin extends javax.swing.JFrame {

    analisisfasilitasruangan fasilitas = new analisisfasilitasruangan();
     analisakondisiruang kondisi = new analisakondisiruang();
     analisisidentitasruangan identitas =new analisisidentitasruangan();
    public framelogin() {
        initComponents();
        
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaruangan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lokasiruangan = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        programstudi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        kunci = new javax.swing.JComboBox();
        jendela = new javax.swing.JComboBox();
        bahaya = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        namaframe = new javax.swing.JLabel();
        loginform = new javax.swing.JLabel();
        unamefield = new javax.swing.JTextField();
        uname = new javax.swing.JLabel();
        passfield = new javax.swing.JTextField();
        loginbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        pjg1 = new javax.swing.JLabel();
        lbar1 = new javax.swing.JLabel();
        isipjg = new javax.swing.JTextField();
        isilebar = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        petunjuk = new javax.swing.JLabel();
        klantai = new javax.swing.JLabel();
        katap = new javax.swing.JLabel();
        kdinding = new javax.swing.JLabel();
        kjendela = new javax.swing.JLabel();
        kpintu = new javax.swing.JLabel();
        isilantai = new javax.swing.JTextField();
        isiatap = new javax.swing.JTextField();
        isidinding = new javax.swing.JTextField();
        isijendela = new javax.swing.JTextField();
        isipintu = new javax.swing.JTextField();
        bisingan = new javax.swing.JLabel();
        kbau = new javax.swing.JLabel();
        kerusak = new javax.swing.JLabel();
        keaus = new javax.swing.JLabel();
        koh = new javax.swing.JLabel();
        isibising = new javax.swing.JTextField();
        isibau = new javax.swing.JTextField();
        isirusak = new javax.swing.JTextField();
        isiaus = new javax.swing.JTextField();
        isikokoh = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        isiudra = new javax.swing.JTextField();
        petunjuk2 = new javax.swing.JLabel();
        suhu = new javax.swing.JLabel();
        isisuhu = new javax.swing.JTextField();
        petunjuk3 = new javax.swing.JLabel();
        intenchy = new javax.swing.JLabel();
        isichy = new javax.swing.JTextField();
        lmbb = new javax.swing.JLabel();
        isilmbb = new javax.swing.JTextField();
        next1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ks = new javax.swing.JComboBox();
        ps = new javax.swing.JComboBox();
        kka = new javax.swing.JComboBox();
        pka = new javax.swing.JComboBox();
        klcd = new javax.swing.JComboBox();
        plcd = new javax.swing.JComboBox();
        pl = new javax.swing.JComboBox();
        kl = new javax.swing.JComboBox();
        kac = new javax.swing.JComboBox();
        pac = new javax.swing.JComboBox();
        pc = new javax.swing.JComboBox();
        kc = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ssid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jmlp = new javax.swing.JTextField();
        jmlka = new javax.swing.JTextField();
        jmlklc = new javax.swing.JTextField();
        jmlac = new javax.swing.JTextField();
        jmls = new javax.swing.JTextField();
        jmll = new javax.swing.JTextField();
        jmlc = new javax.swing.JTextField();
        jmlj = new javax.swing.JTextField();
        jmlk = new javax.swing.JTextField();
        dl = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("IDENTITAS RUANGAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        namaruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaruanganActionPerformed(evt);
            }
        });
        jPanel2.add(namaruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 30));

        jLabel26.setText("Nama Ruangan");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 20));

        jLabel27.setText("Lokasi Ruangan");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, -1));

        lokasiruangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GKB 1", "GKB 2", "GKB 3", " " }));
        lokasiruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiruanganActionPerformed(evt);
            }
        });
        jPanel2.add(lokasiruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        jLabel28.setText("Program Studi");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, 20));

        programstudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programstudiActionPerformed(evt);
            }
        });
        jPanel2.add(programstudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, 30));

        jLabel29.setText("kunci pintu");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 80, -1));

        jLabel30.setText("Jendela");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 70, -1));

        jLabel31.setText("Bahaya");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        kunci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        kunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunciActionPerformed(evt);
            }
        });
        jPanel2.add(kunci, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 40, -1));

        jendela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        jPanel2.add(jendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, -1));

        bahaya.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        jPanel2.add(bahaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, -1));

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, 20));

        jLabel35.setText("* 0 = tidak ada / 1 = ada");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel36.setText("* 0 = tidak ada / 1 = ada");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel37.setText("* 0 = tidak ada / 1 = ada");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaframe.setText("LOG IN INVENTARIS");
        jPanel1.add(namaframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 0, 158, 34));

        loginform.setText("Masukkan Password :");
        jPanel1.add(loginform, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 123, 22));

        unamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(unamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, -1));

        uname.setText("Masukkan Username :");
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 123, 23));
        jPanel1.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, -1));

        loginbutton.setText("LOG IN");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setText("PENILAIAN KONDISI RUANGAN");
        jPanel3.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        pjg1.setText("Masukkan Panjang");
        jPanel3.add(pjg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbar1.setText("Masukkan Lebar");
        jPanel3.add(lbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));
        jPanel3.add(isipjg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 40, 20));

        isilebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isilebarActionPerformed(evt);
            }
        });
        jPanel3.add(isilebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 40, -1));
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        petunjuk.setText("*Masukkan nilai antara 10-100");
        jPanel3.add(petunjuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        klantai.setText("Kondisi Lantai");
        jPanel3.add(klantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        katap.setText("Kondisi Atap");
        jPanel3.add(katap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        kdinding.setText("Kondisi Dinding");
        jPanel3.add(kdinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        kjendela.setText("Kondisi Jendela");
        jPanel3.add(kjendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        kpintu.setText("Kondisi Pintu");
        jPanel3.add(kpintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanel3.add(isilantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 40, -1));
        jPanel3.add(isiatap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, -1));
        jPanel3.add(isidinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 40, -1));
        jPanel3.add(isijendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 40, -1));
        jPanel3.add(isipintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 40, -1));

        bisingan.setText("Kebisingan");
        jPanel3.add(bisingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        kbau.setText("Bau");
        jPanel3.add(kbau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        kerusak.setText("Kerusakan");
        jPanel3.add(kerusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 354, -1, 20));

        keaus.setText("Keausan");
        jPanel3.add(keaus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        koh.setText("Kekokohan");
        jPanel3.add(koh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        jPanel3.add(isibising, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 40, -1));
        jPanel3.add(isibau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 40, -1));
        jPanel3.add(isirusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 40, -1));
        jPanel3.add(isiaus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 40, -1));
        jPanel3.add(isikokoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 40, -1));

        jLabel33.setText("Udara");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        jPanel3.add(isiudra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 40, -1));

        petunjuk2.setText("*Masukkan antara 25-35");
        jPanel3.add(petunjuk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        suhu.setText("Suhu Ruangan");
        jPanel3.add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));
        jPanel3.add(isisuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, -1));

        petunjuk3.setText("*Masukkan antara 250-350");
        jPanel3.add(petunjuk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        intenchy.setText("Intensitas Cahaya");
        jPanel3.add(intenchy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));
        jPanel3.add(isichy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 40, -1));

        lmbb.setText("Kelembaban");
        jPanel3.add(lmbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        jPanel3.add(isilmbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 40, -1));

        next1.setText("NEXT");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        jPanel3.add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel2.setText("FASILITAS RUANGAN");

        jLabel3.setText("jumlah steker");

        jLabel4.setText("kondisi steker");

        jLabel5.setText("posisi steker");

        jLabel6.setText("jumlah kabel lcd");

        jLabel7.setText("jumlah kipas angin");

        jLabel8.setText("jumlah AC");

        jLabel9.setText("jumlah lampu");

        jLabel10.setText("jumlah CCTV");

        jLabel11.setText("kondisi  kabel lcd");

        jLabel12.setText("kondisi kipas angin");

        jLabel13.setText("kondisi AC");

        jLabel14.setText("kondisi lampu");

        jLabel15.setText("kondisi CCTV");

        jLabel16.setText("posisi kipas angin");

        jLabel17.setText("posisi  kabel lcd");

        jLabel18.setText("posisi AC");

        jLabel19.setText("posisi lampu");

        jLabel20.setText("posisi CCTV");

        ks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        ks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ksActionPerformed(evt);
            }
        });

        ps.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        kka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        pka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        klcd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        plcd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        pl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        kl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        kac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        pac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        pc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        kc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        kc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kcActionPerformed(evt);
            }
        });

        jLabel21.setText("jumlah pintu");

        jLabel22.setText("jumlah kursi");

        jLabel23.setText("jumlah jendela");

        jLabel24.setText("dapat login");

        jLabel25.setText("SSID");

        ssid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssidActionPerformed(evt);
            }
        });

        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jmlka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkaActionPerformed(evt);
            }
        });

        jmls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlsActionPerformed(evt);
            }
        });

        dl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        dl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(28, 28, 28)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmlp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmlk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(plcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmls, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(klcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmlklc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12))
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(pka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jmlka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(280, 280, 280))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jmlka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(kka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addComponent(pka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jmlklc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(kac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(plcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jmll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jmlk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel38.setText("PETUNJUK UNTUK FASILITAS");

        jLabel39.setText("1. Semua Kondisi : 1 = rusak / 2 = baik");

        jLabel40.setText("2. Posisi pada steker : 1 = pojok ruangan / 2 = tengah / 3 = dekat dosen");

        jLabel41.setText("3. Posisi pada lcd : 1 = jauh dari dosen / 2 = dekat dari dosen");

        jLabel42.setText("4. Posisi pada lampu dan kipas angin : 1 = tembok / 2 = atap");

        jLabel43.setText("5. Posisi pada AC : 1 = depan samping / 2 = depan tengah / 3 = belakang tengah ");

        jLabel44.setText("/ 4 = belakang samping");

        jLabel45.setText("6. Posisi pada CCTV : 1 = depan / 2 = tengah / 3 = belakang");

        jLabel46.setText("7. Login : 1 = tidak dapat login / 2 = dapat login");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(161, 161, 161))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel44))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel43)
                                .addComponent(jLabel41)
                                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel46))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(19, 19, 19)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addGap(8, 8, 8)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 529, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 530, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(481, 481, 481)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 211, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 211, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        if(unamefield.getText().equals("roy") && passfield.getText().equals("naruto")){
            JOptionPane.showMessageDialog(null,"Selamat Log In Berhasil");
        }
        else{
            JOptionPane.showMessageDialog(null,"Maaf ada kesalahan dalam username atau Password");
        }
        jPanel1.setVisible(false);
       jPanel2.setVisible(true);
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void unamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unamefieldActionPerformed

    private void ssidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssidActionPerformed

    private void ksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ksActionPerformed

    private void kcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
fasilitas.setJumlahsteker(Integer.parseInt(jmls.getText()));
fasilitas.setKondisisteker(Integer.parseInt(ks.getSelectedItem().toString()));
fasilitas.setPosisisteker(Integer.parseInt(ps.getSelectedItem().toString()));

fasilitas.setJumlahkabellcd(Integer.parseInt(jmll.getText()));
fasilitas.setKondisikabellcd(Integer.parseInt(klcd.getSelectedItem().toString()));
fasilitas.setPosisikabellcd(Integer.parseInt(plcd.getSelectedItem().toString()));

fasilitas.setJumlahlampu(Integer.parseInt(jmll.getText()));
fasilitas.setKondisilampu(Integer.parseInt(kl.getSelectedItem().toString()));
fasilitas.setPosisilampu(Integer.parseInt(pl.getSelectedItem().toString()));

fasilitas.setJumlahkipasangin(Integer.parseInt(jmlka.getText()));
fasilitas.setKondisikipasangin(Integer.parseInt(kka.getSelectedItem().toString()));
fasilitas.setPosisikipasangin(Integer.parseInt(pka.getSelectedItem().toString()));

fasilitas.setJumlahac(Integer.parseInt(jmlac.getText()));
fasilitas.setKondisiac(Integer.parseInt(kac.getSelectedItem().toString()));
fasilitas.setPosisiac(Integer.parseInt(pac.getSelectedItem().toString()));

fasilitas.setJumlahcctv(Integer.parseInt(jmlc.getText()));
fasilitas.setKondisicctv(Integer.parseInt(kc.getSelectedItem().toString()));
fasilitas.setPosisicctv(Integer.parseInt(pc.getSelectedItem().toString()));

fasilitas.setJumlahpintu(Integer.parseInt(jmlp.getText()));
fasilitas.setJumlahjendela(Integer.parseInt(jmlj.getText()));
fasilitas.setJumlahkursi(Integer.parseInt(jmlk.getText()));

fasilitas.setSSID(ssid.getText());
fasilitas.setLogin(Integer.parseInt(dl.getSelectedItem().toString()));

fasilitas.Analisiskelistrikan();
fasilitas.Analisislcd();
fasilitas.Analisislampu();
fasilitas.Analisiskipasangin();
fasilitas.Analisisac();
fasilitas.Analisisinternet();
fasilitas.Analisiscctv();
fasilitas.pintu();
fasilitas.jendela();

fasilitas.save();
fasilitas.readme();

       

       
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmlkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlkaActionPerformed

    private void dlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlActionPerformed

    private void lokasiruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiruanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasiruanganActionPerformed

    private void programstudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programstudiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programstudiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
identitas.setNamaruangan(namaruangan.getText());
identitas.setLokasi_ruangan(lokasiruangan.getSelectedItem().toString());
identitas.setProgram_studi(programstudi.getText());
identitas.setKunci_pintu(Integer.parseInt(kunci.getSelectedItem().toString()));
identitas.setJendela(Integer.parseInt(jendela.getSelectedItem().toString()));
identitas.setBahaya(Integer.parseInt(bahaya.getSelectedItem().toString()));
identitas.simpan1();
identitas.read();
jPanel2.setVisible(false);
jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namaruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaruanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaruanganActionPerformed

    private void jmlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlsActionPerformed

    private void kunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kunciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kunciActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
    kondisi.setPanjang(Integer.parseInt(isipjg.getText()));
    kondisi.setLebar(Integer.parseInt(isilebar.getText()));
    kondisi.setKondisiLantai(Integer.parseInt(isilantai.getText()));
    kondisi.setKondisiAtap(Integer.parseInt(isiatap.getText()));
    kondisi.setKondisiJendela(Integer.parseInt(isijendela.getText()));
    kondisi.setKondisiDinding(Integer.parseInt(isidinding.getText()));
    kondisi.setKondisiPintu(Integer.parseInt(isipintu.getText()));
    kondisi.setKebisingan(Integer.parseInt(isibising.getText()));
    kondisi.setBau(Integer.parseInt(isibau.getText()));
    kondisi.setKerusakan(Integer.parseInt(isirusak.getText()));
    kondisi.setKeausan(Integer.parseInt(isiaus.getText()));
    kondisi.setKekokohan(Integer.parseInt(isikokoh.getText()));
    kondisi.setSuhu(Integer.parseInt(isisuhu.getText()));
    kondisi.setKelembaban(Integer.parseInt(isilmbb.getText()));
    kondisi.setNilaiPencahayaan(Integer.parseInt(isichy.getText()));
    kondisi.setSirkulasiUdara(Integer.parseInt(isiudra.getText()));
    kondisi.simpan();
    kondisi.readme();
    
    jPanel3.setVisible(false);
jPanel4.setVisible(true);
    }//GEN-LAST:event_next1ActionPerformed

    private void isilebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isilebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isilebarActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bahaya;
    private javax.swing.JLabel bisingan;
    private javax.swing.JComboBox dl;
    private javax.swing.JLabel intenchy;
    private javax.swing.JTextField isiatap;
    private javax.swing.JTextField isiaus;
    private javax.swing.JTextField isibau;
    private javax.swing.JTextField isibising;
    private javax.swing.JTextField isichy;
    private javax.swing.JTextField isidinding;
    private javax.swing.JTextField isijendela;
    private javax.swing.JTextField isikokoh;
    private javax.swing.JTextField isilantai;
    private javax.swing.JTextField isilebar;
    private javax.swing.JTextField isilmbb;
    private javax.swing.JTextField isipintu;
    private javax.swing.JTextField isipjg;
    private javax.swing.JTextField isirusak;
    private javax.swing.JTextField isisuhu;
    private javax.swing.JTextField isiudra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox jendela;
    private javax.swing.JTextField jmlac;
    private javax.swing.JTextField jmlc;
    private javax.swing.JTextField jmlj;
    private javax.swing.JTextField jmlk;
    private javax.swing.JTextField jmlka;
    private javax.swing.JTextField jmlklc;
    private javax.swing.JTextField jmll;
    private javax.swing.JTextField jmlp;
    private javax.swing.JTextField jmls;
    private javax.swing.JLabel judul;
    private javax.swing.JComboBox kac;
    private javax.swing.JLabel katap;
    private javax.swing.JLabel kbau;
    private javax.swing.JComboBox kc;
    private javax.swing.JLabel kdinding;
    private javax.swing.JLabel keaus;
    private javax.swing.JLabel kerusak;
    private javax.swing.JLabel kjendela;
    private javax.swing.JComboBox kka;
    private javax.swing.JComboBox kl;
    private javax.swing.JLabel klantai;
    private javax.swing.JComboBox klcd;
    private javax.swing.JLabel koh;
    private javax.swing.JLabel kpintu;
    private javax.swing.JComboBox ks;
    private javax.swing.JComboBox kunci;
    private javax.swing.JLabel lbar1;
    private javax.swing.JLabel lmbb;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginform;
    private javax.swing.JComboBox lokasiruangan;
    private javax.swing.JLabel namaframe;
    private javax.swing.JTextField namaruangan;
    private javax.swing.JToggleButton next1;
    private javax.swing.JComboBox pac;
    private javax.swing.JTextField passfield;
    private javax.swing.JComboBox pc;
    private javax.swing.JLabel petunjuk;
    private javax.swing.JLabel petunjuk2;
    private javax.swing.JLabel petunjuk3;
    private javax.swing.JLabel pjg1;
    private javax.swing.JComboBox pka;
    private javax.swing.JComboBox pl;
    private javax.swing.JComboBox plcd;
    private javax.swing.JTextField programstudi;
    private javax.swing.JComboBox ps;
    private javax.swing.JTextField ssid;
    private javax.swing.JLabel suhu;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField unamefield;
    // End of variables declaration//GEN-END:variables
}
